name: Postar Reel no Instagram

on:
   schedule:
    - cron: '0 20 * * *'  
   push:
    branches:
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest 
    steps:
     
      - name: Checar código
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assumindo que você tem um arquivo requirements.txt
      
      - name: Rodar script Python
        run: python main.py  
