name: Post Instagram reel
on:
  push:
    branches:
      - 'main'
jobs:
  run-script:
    runs-on: ubuntu-latest 
    steps:
     
      - name: Check the code
        uses: actions/checkout@v2

      - name: Config python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9  

      - name: Install packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Assumindo que você tem um arquivo requirements.txt
      
      - name: Run script
        env:
          IG_USERNAME: ${{ secrets.IG_USERNAME }}
          IG_PASSWORD: ${{ secrets.IG_PASSWORD }}
        run: python main.py  
